### ISSUE TITLE
lstm_step_backward line# 343 += is mistake or intend?

### ISSUE THREAD

**Issue by sangche** [cthorey/CS231#1]
Your  lstm_step_backward line# 343 is written as

`# Backprop into step 5`
`dnext_c += o * (1 - np.tanh(next_c)**2) * dnext_h`

which means,
`dnext_c = dnext_c + o * (1 - np.tanh(next_c)**2) * dnext_h`

But, from your lstm_step_forward line# 304:
`next_h = o * np.tanh(next_c)`

I think dnext_c from line# 304 is just
`dnext_c = o * (1 - np.tanh(next_c)**2) * dnext_h`

If you intend it, what am I wrong?

**Comment by sangche** [comment]
your code `dnext_c += o * (1 - np.tanh(next_c)**2) * dnext_h` is right.
cell branches in lstm circuit.

**Comment by cthorey** [comment]
Indeed ;)
